### PR TITLE
Dockerfile improvements and automatic Github Actions builds

### PR DESCRIPTION
**Pull request by sethforprivacy**
This improves the Dockerfile slightly while adding automatic builds via Github Actions to allow you to easily distribute pre-built images.

If that is not something you want, please let me know and I will close this PR and maintain images on my own!

If you do want that, you will need to setup a Docker Hub account (if you wish) or just rely on Github Container Registry. If you want to use Docker Hub, simply create an account, create a Personal Access Token, and add it to the Action Secrets in your repo with the variables `DOCKER_USERNAME` and `DOCKER_PASSWORD`.

Once added, whenever you push to main/master Github will automatically build and push under the `latest` tag and a tag made of the short SHA of the latest commit (i.e. [here](https://hub.docker.com/repository/docker/sethforprivacy/public-pool/general)).

If no changes are made, it will also automatically rebuild and push the images weekly to keep the base image up to date with security patches etc.

### CODE REVIEW

**Comment by benjamin-wilson** [comment]
@sethforprivacy looks like there's something wrong with the build
`buildx failed with: ERROR: invalid tag "/public-pool:latest": invalid reference format`

**Comment by sethforprivacy** [comment]
> @sethforprivacy looks like there's something wrong with the build `buildx failed with: ERROR: invalid tag "/public-pool:latest": invalid reference format`

Ah, that is just failing as it relies on pulling the image from GHCR or Docker Hub, neither of which have the image available from your repo yet.

The important test succeeded, and the vuln scan will succeed after you've pushed an initial image manually or via these Actions.

**Comment by sethforprivacy** [comment]
Well that was fast :smile: 

Let me know if you run into any issues with the builds, happy to help troubleshoot and you know how to reach me directly!

**Comment by sethforprivacy** [comment]
> unauthorized: incorrect username or password

Looks like the Docker creds need to be added/updated for it to run (or you can strip out the Docker Hub login + lines pushing to it in the buildx steps)

**Comment by benjamin-wilson** [comment]
🤔 I added them to the rep secrets and the access token as the password

**Comment by sethforprivacy** [comment]
Should be here:

image

**Comment by sethforprivacy** [comment]
If there it's possible you haven't scoped the access token properly, or you haven't created the repo in Docker Hub (forgot that you have to do that manually!)

**Comment by benjamin-wilson** [comment]
Yeah that's what I did 🤔🤔

**Comment by benjamin-wilson** [comment]
Oh gotta create the repo!

**Comment by sethforprivacy** [comment]
> Oh gotta create the repo!

Yeah, that's my bad! Totally forgot that it won't automatically create it for you -.-

**Pull request merged**
